export const KEYS_DICT = [
  { name: "Esc", code: "KC_ESC", keys: "esc", input: "Escape" },
  { name: "F1", code: "KC_F1", keys: "f1", input: "F1" },
  { name: "F2", code: "KC_F2", keys: "f2", input: "F2" },
  { name: "F3", code: "KC_F3", keys: "f3", input: "F3" },
  { name: "F4", code: "KC_F4", keys: "f4", input: "F4" },
  { name: "F5", code: "KC_F5", keys: "f5", input: "F5" },
  { name: "F6", code: "KC_F6", keys: "f6", input: "F6" },
  { name: "F7", code: "KC_F7", keys: "f7", input: "F7" },
  { name: "F8", code: "KC_F8", keys: "f8", input: "F8" },
  { name: "F9", code: "KC_F9", keys: "f9", input: "F9" },
  { name: "F10", code: "KC_F10", keys: "f10", input: "F10" },
  { name: "F11", code: "KC_F11", keys: "f11", input: "F11" },
  { name: "F12", code: "KC_F12", keys: "f12", input: "F12" },
  { name: "Print Screen", code: "KC_PSCR", keys: "⎙", input: "Print Screen" },
  { name: "Scroll Lock", code: "KC_SCRL", keys: "⤓", input: "Scroll Lock" },
  { name: "Pause", code: "KC_PAUS", keys: "❚❚", input: "Pause" },
  {
    name: "~\n`",
    code: "KC_GRV",
    keys: "`",
    input: "`",
  },
  {
    name: "~\n`",
    code: "KC_TILD",
    keys: "~",
    input: "~",
  },
  { name: "!\n1", code: "KC_1", keys: "1", input: "1" },
  { name: "@\n2", code: "KC_2", keys: "2", input: "2" },
  { name: "#\n3", code: "KC_3", keys: "3", input: "3" },
  { name: "$\n4", code: "KC_4", keys: "4", input: "4" },
  { name: "%\n5", code: "KC_5", keys: "5", input: "5" },
  { name: "^\n6", code: "KC_6", keys: "6", input: "6" },
  { name: "&\n7", code: "KC_7", keys: "7", input: "7" },
  { name: "*\n8", code: "KC_8", keys: "8", input: "8" },
  { name: "(\n9", code: "KC_9", keys: "9", input: "9" },
  { name: ")\n0", code: "KC_0", keys: "0", input: "0" },
  { name: "_\n-", code: "KC_MINS", keys: "-", input: "-" },
  { name: "+\n=", code: "KC_EQL", keys: "=", input: "=" },
  {
    name: "Back Space",
    code: "KC_BSPC",
    keys: "backspace",
    input: "Backspace",
  },
  { name: "Insert", code: "KC_INS", keys: "insert", input: "Insert" },
  { name: "Home", code: "KC_HOME", keys: "home", input: "Home" },
  { name: "Page Up", code: "KC_PGUP", keys: "pageup", input: "PageUp" },
  { name: "Num Lock", code: "KC_NUM", keys: "num", input: "NumLock" },
  { name: "/", code: "KC_PSLS", keys: "num_divide", input: "/" },
  { name: "*", code: "KC_PAST", keys: "num_multiply", input: "*" },
  { name: "-", code: "KC_PMNS", keys: "num_subtract", input: "-" },
  { name: "Tab", code: "KC_TAB", keys: "tab", input: "Tab" },
  { name: "q", code: "KC_Q", keys: "q", input: "q" },
  { name: "w", code: "KC_W", keys: "w", input: "w" },
  { name: "e", code: "KC_E", keys: "e", input: "e" },
  { name: "r", code: "KC_R", keys: "r", input: "r" },
  { name: "t", code: "KC_T", keys: "t", input: "t" },
  { name: "y", code: "KC_Y", keys: "y", input: "y" },
  { name: "u", code: "KC_U", keys: "u", input: "u" },
  { name: "i", code: "KC_I", keys: "i", input: "i" },
  { name: "o", code: "KC_O", keys: "o", input: "o" },
  { name: "p", code: "KC_P", keys: "p", input: "p" },
  { name: "{\n[", code: "KC_LBRC", keys: "[", input: "[" },
  { name: "}\n]", code: "KC_RBRC", keys: "]", input: "]" },
  { name: "|\n\\", code: "KC_BSLS", keys: "\\", input: "\\" },
  { name: "Delete", code: "KC_DEL", keys: "delete", input: "Delete" },
  { name: "End", code: "KC_END", keys: "end", input: "End" },
  { name: "Page Down", code: "KC_PGDN", keys: "pagedown", input: "PageDown" },
  { name: "7\nHome", code: "KC_P7", keys: "num_7", input: "7" },
  { name: "8\n⏶", code: "KC_P8", keys: "num_8", input: "8" },
  { name: "9\nPgUp", code: "KC_P9", keys: "num_9", input: "9" },
  { name: "+", code: "KC_PPLS", keys: "num_add", input: "+" },
  { name: "Caps Lock", code: "KC_CAPS", keys: "caps_lock", input: "Caps Lock" },
  { name: "a", code: "KC_A", keys: "a", input: "a" },
  { name: "s", code: "KC_S", keys: "s", input: "s" },
  { name: "d", code: "KC_D", keys: "d", input: "d" },
  { name: "f", code: "KC_F", keys: "f", input: "f" },
  { name: "g", code: "KC_G", keys: "g", input: "g" },
  { name: "h", code: "KC_H", keys: "h", input: "h" },
  { name: "j", code: "KC_J", keys: "j", input: "j" },
  { name: "k", code: "KC_K", keys: "k", input: "k" },
  { name: "l", code: "KC_L", keys: "l", input: "l" },
  { name: ":\n;", code: "KC_SCLN", keys: ";", input: ";" },
  { name: "\"\n'", code: "KC_QUOT", keys: "'", input: '"' },
  { name: "Enter\n↵", code: "KC_ENT", keys: "enter", input: "Enter" },
  { name: "4\n⏴", code: "KC_P4", keys: "num_4", input: "4" },
  { name: "5", code: "KC_P5", keys: "num_5", input: "5" },
  { name: "6\n⏵", code: "KC_P6", keys: "num_6", input: "6" },
  { name: ",", code: "KC_PCMM", keys: ",", input: "," },
  { name: "Left Shift", code: "KC_LSFT", keys: "⇧", input: "Shift" },
  { name: "z", code: "KC_Z", keys: "z", input: "z" },
  { name: "x", code: "KC_X", keys: "x", input: "x" },
  { name: "c", code: "KC_C", keys: "c", input: "c" },
  { name: "v", code: "KC_V", keys: "v", input: "v" },
  { name: "b", code: "KC_B", keys: "b", input: "b" },
  { name: "n", code: "KC_N", keys: "n", input: "n" },
  { name: "m", code: "KC_M", keys: "m", input: "m" },
  { name: "<\n,", code: "KC_COMM", keys: ",", input: "," },
  { name: ">\n.", code: "KC_DOT", keys: ".", input: "." },
  { name: "?\n/", code: "KC_SLSH", keys: "/", input: "/" },
  { name: "Right Shift", code: "KC_RSFT", keys: "⇧", input: "Shift" },
  { name: "⏶", code: "KC_UP", keys: "⏶", input: "ArrowUp" },
  { name: "1\nEnd", code: "KC_P1", keys: "num_1", input: "1" },
  { name: "2\n⏷", code: "KC_P2", keys: "num_2", input: "2" },
  { name: "3\nPgDn", code: "KC_P3", keys: "num_3", input: "3" },
  { name: "=", code: "KC_PEQL", keys: "=", input: "=" },
  { name: "Control", code: "KC_LCTL", keys: "ctrl", input: "Control" },
  { name: "Meta", code: "KC_LGUI", keys: "cmd", input: "Meta" },
  { name: "Alt", code: "KC_LALT", keys: "alt", input: "Alt" },
  { name: "Space", code: "KC_SPC", keys: "space", input: " " },
  { name: "Alt", code: "KC_RALT", keys: "alt", input: "Alt" },
  { name: "Meta", code: "KC_RGUI", keys: "meta", input: "Meta" },
  { name: "≡", code: "KC_APP", keys: "Context Menu", input: "Context" },
  { name: "Control", code: "KC_RCTL", keys: "ctrl", input: "Control" },
  { name: "⏴", code: "KC_LEFT", keys: "⏴", input: "ArrowLeft" },
  { name: "⏷", code: "KC_DOWN", keys: "⏷", input: "ArrowDown" },
  { name: "⏵", code: "KC_RGHT", keys: "⏵", input: "ArrowRight" },
  { name: "0\nIns", code: "KC_P0", keys: "num_0", input: "0" },
  { name: ".\nDel", code: "KC_PDOT", keys: "num_decimal", input: "." },
  { name: "Enter", code: "KC_PENT", keys: "num_enter", input: "Enter" },
  { name: "~", code: "KC_TILD", keys: "~", input: "~" },
  { name: "!", code: "KC_EXLM", keys: "!", input: "!" },
  { name: "@", code: "KC_AT", keys: "@", input: "@" },
  { name: "#", code: "KC_HASH", keys: "#", input: "#" },
  { name: "$", code: "KC_DLR", keys: "$", input: "$" },
  { name: "%", code: "KC_PERC", keys: "%", input: "%" },
  { name: "^", code: "KC_CIRC", keys: "^", input: "^" },
  { name: "&", code: "KC_AMPR", keys: "&", input: "&" },
  { name: "*", code: "KC_ASTR", keys: "*", input: "*" },
  { name: "(", code: "KC_LPRN", keys: "(", input: "(" },
  { name: ")", code: "KC_RPRN", keys: ")", input: ")" },
  { name: "_", code: "KC_UNDS", keys: "_", input: "_" },
  { name: "+", code: "KC_PLUS", keys: "+", input: "+" },
  { name: "{", code: "KC_LCBR", keys: "{", input: "{" },
  { name: "}", code: "KC_RCBR", keys: "}", input: "}" },
  { name: "<", code: "KC_LT", keys: "<", input: "<" },
  { name: ">", code: "KC_GT", keys: ">", input: ">" },
  { name: ":", code: "KC_COLN", keys: ":", input: ":" },
  { name: "|", code: "KC_PIPE", keys: "|", input: "|" },
  { name: "?", code: "KC_QUES", keys: "?", input: "?" },
  { name: '"', code: "KC_DQUO", keys: '"', input: '"' },

  // Special characters
  { name: "▽", code: "KC_TRNS", keys: "", input: "" },
];
